### ISSUE TITLE
Add ability to pass in params via CLI to override params in tests file

### ISSUE THREAD

**Issue by brint** [brint/hot#2]
Allow a user to override parameters via command line. Example test config:

```
test-cases:
- name: Standard Instance, non-standard Port
  create:
    parameters:
      port: 1234
      user: sample
    timeout: 30
```

Allow a user to override the default by running:

```
hot test -P port=1235 -P user=test
```
